org: maquiadev1
app: aws-monitors4
service: aws-monitors4

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - {"Fn::GetAtt": ["ms4notificationTable", "Arn"]}
        - {"Fn::GetAtt": ["ms4companiesTable", "Arn"]}

functions:
  addNotification:
    handler: src/addNotification.handler
    events:
      - httpApi:
          path: /addNotification
          method: post

resources:
  Resources:
    ms4notificationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ms4notificationTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ms4companiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ms4companiesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
